### ISSUE TITLE
Clicking quickly between tools and workflows on search causes an error

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#4619]
**Describe the bug**

When cycling quickly between tools and workflows on the search page an error in the console is observed and the controls are no longer responsive.

```ERROR TypeError: o.checkboxMap.get(...) is undefined```

**To Reproduce**

1. Go to search
2. Open console to observe error
2. Select between workflows and tools quickly

**Expected behavior**

Should remain responsive even when rapid input is provided, or block input while loading.

**Screenshots**

![image](https://user-images.githubusercontent.com/3795586/145480041-6b61dcb3-a95a-4c68-ac73-fa251958859f.png)

**Smartphone (please complete the following information):**

Firefox/ubuntu

**Additional context**

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.9) - 1.11.9

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.3) - 2.8.3

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11.1) - 1.11.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.2) - 1.11.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2012)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2012
┆sprint: 93- Ursula
┆taskType: Story

**Comment by garyluu** [comment]
Should be fixed in my search refactor PR (if it ever gets merged). Otherwise, could stick some "?" in the html.

**Comment by david4096** [comment]
I looked over the WAF logs and discovered this bug, or a similar one that causes end users to spam the search endpoint likely still occurs.
